// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaNJEtLHlPtTojg5SP_XJUArsDBNzqwFo',
    appId: '1:26171345893:web:9b4fc5f81373310567fd0c',
    messagingSenderId: '26171345893',
    projectId: 'group-chat-df9c6',
    authDomain: 'group-chat-df9c6.firebaseapp.com',
    storageBucket: 'group-chat-df9c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHN5YfytYkRyV_LkMU8DMER39NqFCFbHI',
    appId: '1:26171345893:android:6b1d98adafa88eef67fd0c',
    messagingSenderId: '26171345893',
    projectId: 'group-chat-df9c6',
    storageBucket: 'group-chat-df9c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh6FQWha1SxeUhVyBLVo1mK5fI0107VcM',
    appId: '1:26171345893:ios:ce33c957f0d7bd6267fd0c',
    messagingSenderId: '26171345893',
    projectId: 'group-chat-df9c6',
    storageBucket: 'group-chat-df9c6.appspot.com',
    iosClientId: '26171345893-h7ln710c6ikk1ss9kf07vfcmlhca5g20.apps.googleusercontent.com',
    iosBundleId: 'com.example.groupChatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh6FQWha1SxeUhVyBLVo1mK5fI0107VcM',
    appId: '1:26171345893:ios:ce33c957f0d7bd6267fd0c',
    messagingSenderId: '26171345893',
    projectId: 'group-chat-df9c6',
    storageBucket: 'group-chat-df9c6.appspot.com',
    iosClientId: '26171345893-h7ln710c6ikk1ss9kf07vfcmlhca5g20.apps.googleusercontent.com',
    iosBundleId: 'com.example.groupChatApplication',
  );
}
